import focused from '../../public/focused.jpg'
import meeting from '../../public/meeting.jpg'
import pres from '../../public/pres.jpg'
import leader from '../../public/leader.jpg'
import repairing from '../../public/repairing.jpg'
import pacute from '../../public/pacute.jpg'

const AboutText = [
    { id: 0, title:'School', paragraph0: 'I am a graduate of Bachelor of Science in Information Technology. I always love to prove I can do something. I am elected as the president of the Future Information Technologists Organization when I was in second year until I graduated. This is an Oragnization that handles transactions and programs between the school administration and the students of the Department of Computing Science',image0: meeting, paragraph1: 'I am also one of the candidate to be the Best Programmer of the year but unfortunately I am not selected. The funny part is I debugged the error of the candidate that happen to be the programmer of the year. He coppied the program and paste it to the editor and had an error. He reached out and ask what happen so I debugged it. Not to mention his name as he is my friend and it was a reminiscing moment.', image1: pres, paragraph2: 'During my capstone, I was the leader and programmer. I did my best to address every issue in the system, holding meetings and resolving various problems such as syntax errors, logical errors, and paperwork. It was truly exhausting, but it was worth it as I learned a lot. During my OJT, the Dean appointed me to develop an Information System for Student Scholarships. I had the opportunity to visit all the branches of the school, explaining how the system works and how to use it. Additionally, I was granted the Return of Service certificate by Unifast for developing the system, as I was also one of the scholars under their program.', image2: leader},
    { id: 1, title:'Career', paragraph0: 'People in my town and cousins often ask me "You are IT graduate, why dont you go apply in PNP? IT graduate are in demand. "I just do not reply because back then that was actually my plan when I was in college. Take the BSIT course as the stepping stone to enter the PNP. ',image0: pacute, paragraph1: 'Because I am from a school with low quality of teaching in Computer, I taught I am hopeless in IT industry. After I graduated, I work as a freelancer in hardware repairing. I repair desktop, laptop, and gadgets. I also offer home service repair. Last december, one of my friend works as a web developer in a company so I was motivated to pursue programming. During my first months in learning new language (Javascript), it was not that hard as I apply the concepts that I use in C#. Though there are some concepts that are hard to understand (stacked in tutorial hell), I only learned the DOM manipulation using Javscript and jumped to the React Library',image1: repairing, paragraph2: 'It was really hard to choose what to use but as suggested by most of the experienced developers, It is React. Here I learned a lot especifically using different Hooks, state and concept of the virtual DOM. I also learned about the backend using Node Js though not that deep but I know how to make API for CRUD applications and also using API of other Applications.',image2: focused},
];
export default AboutText;